/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.szpital;

import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Map;

/**
 *
 * @author Lenovo
 */
public class DodawanieRezerwacji extends javax.swing.JFrame {

    private Ekran_ordynator_lekarz doctorMainGui;
    private RepoSal repoRooms;
    private RepoRezerwacja reservations;
    private Uzytkownik user;
            
    public DodawanieRezerwacji(Ekran_ordynator_lekarz screen, RepoSal repo) {
        this.doctorMainGui = screen;
        this.repoRooms = repo;
        initComponents();
    }

    //Funkcja aktualizująca i włączająca ekran 
    public void openScreen(RepoRezerwacja repoReservations, Uzytkownik someUser){

        this.user = someUser;
        this.reservations = repoReservations;
        this.setData();
        this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBack = new javax.swing.JButton();
        jDateStartChooser = new com.toedter.calendar.JDateChooser();
        jEndDateChooser = new com.toedter.calendar.JDateChooser();
        jComboRoom = new javax.swing.JComboBox<>();
        jLabelDateStart = new javax.swing.JLabel();
        jLabelEndDate = new javax.swing.JLabel();
        jLabelScreenName = new javax.swing.JLabel();
        jLabelHourStart = new javax.swing.JLabel();
        jLabelEndHour = new javax.swing.JLabel();
        jLabelRoom = new javax.swing.JLabel();
        jComboStartHour = new javax.swing.JComboBox<>();
        jComboEndHour = new javax.swing.JComboBox<>();
        jButtonAdd = new javax.swing.JButton();
        jLabelIdReservation = new javax.swing.JLabel();
        jTextFieldIDreservation = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonBack.setText("Cofnij");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jComboRoom.setModel(new javax.swing.DefaultComboBoxModel<>(this.setRoomNumbers()));
        jComboRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboRoomActionPerformed(evt);
            }
        });

        jLabelDateStart.setText("Data rozpoczęcia:");

        jLabelEndDate.setText("Data zakończenia:");

        jLabelScreenName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelScreenName.setText("Dodawanie rezerwacji");

        jLabelHourStart.setText("Godzina rozpoczęcia:");

        jLabelEndHour.setText("Godzina zakończenia:");

        jLabelRoom.setText("Wybierz numer sali:");

        jComboStartHour.setModel(new javax.swing.DefaultComboBoxModel<>(this.setHours()));

        jComboEndHour.setModel(new javax.swing.DefaultComboBoxModel<>(this.setHours()));

        jButtonAdd.setText("Rezerwuj");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jLabelIdReservation.setText("Wprowadź numer ID rezerwacji:");

        jTextFieldIDreservation.setText("ID rezerwacji");
        jTextFieldIDreservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDreservationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDateStart)
                                    .addComponent(jLabelHourStart, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jComboStartHour, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDateStartChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jEndDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelEndHour, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboEndHour, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabelScreenName, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelIdReservation)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldIDreservation, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelRoom)
                        .addGap(18, 18, 18)
                        .addComponent(jComboRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(286, 286, 286))))
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jButtonAdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelScreenName)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdReservation)
                    .addComponent(jTextFieldIDreservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRoom)
                    .addComponent(jComboRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEndDate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jDateStartChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelDateStart)))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelHourStart)
                            .addComponent(jLabelEndHour)
                            .addComponent(jComboStartHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboEndHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jButtonAdd)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBack))
                    .addComponent(jEndDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIDreservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDreservationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDreservationActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        this.setVisible(false);
        
        doctorMainGui.openScreen();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jComboRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboRoomActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        
        ZoneId zoneId = ZoneId.of("Europe/Warsaw");

        Instant instantStart = jDateStartChooser.getDate().toInstant();
        Instant instantEnd = jEndDateChooser.getDate().toInstant();
        
        LocalDate startDate = instantStart.atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate endDate = instantEnd.atZone(zoneId.systemDefault()).toLocalDate();
        
        DateTimeFormatter formatter1 = DateTimeFormatter.ofPattern("HH:mm");
        
        String startTimeString = (String) jComboStartHour.getSelectedItem();
        String endTimeString = (String) jComboEndHour.getSelectedItem();
        LocalTime startTime = LocalTime.parse(startTimeString, formatter1);
        LocalTime endTime = LocalTime.parse(endTimeString, formatter1);
        int id = this.reservations.getReservations().size()+1;
        int number =  Integer.parseInt(jComboRoom.getSelectedItem().toString());
        Sala room = this.repoRooms.searchForRoom(number);
        
        this.reservations.addReservation(id, this.user.getName() , this.user.getSurname(), startDate, endDate, startTime, endTime, room);
    }//GEN-LAST:event_jButtonAddActionPerformed

    private String[] setHours(){
        
        String[] startHours = new String[] {"06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00", "24:00"};
        
        return startHours;
    }
    
    private String[] setRoomNumbers(){
        
        String[] roomNumbers = new String[this.repoRooms.getRooms().size()];
        int count = 0;
        
        for(Map.Entry<Integer, Sala> entry : this.repoRooms.getRooms().entrySet()){
                roomNumbers[count] = Integer.toString(entry.getValue().getNumber());
                count++;
        }
        return roomNumbers;
}

    
    private void setData(){
        int id = this.reservations.getReservations().size()+1;
        jTextFieldIDreservation.setEditable(false);
        jTextFieldIDreservation.setText(Integer.toString(id));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JComboBox<String> jComboEndHour;
    private javax.swing.JComboBox<String> jComboRoom;
    private javax.swing.JComboBox<String> jComboStartHour;
    private com.toedter.calendar.JDateChooser jDateStartChooser;
    private com.toedter.calendar.JDateChooser jEndDateChooser;
    private javax.swing.JLabel jLabelDateStart;
    private javax.swing.JLabel jLabelEndDate;
    private javax.swing.JLabel jLabelEndHour;
    private javax.swing.JLabel jLabelHourStart;
    private javax.swing.JLabel jLabelIdReservation;
    private javax.swing.JLabel jLabelRoom;
    private javax.swing.JLabel jLabelScreenName;
    private javax.swing.JTextField jTextFieldIDreservation;
    // End of variables declaration//GEN-END:variables
}
