/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.szpital;

/**
 *
 * @author Lenovo
 */
public class SprzetRezerwacje extends javax.swing.JFrame {

    private Ekran_ordynator_lekarz doctorMainGui;
    
    public SprzetRezerwacje(Ekran_ordynator_lekarz screen) {
        this.doctorMainGui = screen;
        initComponents();
    }
    
    //Funkcja aktualizująca i włączająca ekran 
    public void openScreen(){
        
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEqNameField3 = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jIDeqField = new javax.swing.JTextField();
        jLabelChooseIDeq = new javax.swing.JLabel();
        jLabelAddEq = new javax.swing.JLabel();
        jLabelSetEqName = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jPutIDresField5 = new javax.swing.JTextField();
        jButtonResListEq = new javax.swing.JButton();
        jLabelChooseIDres = new javax.swing.JLabel();
        jIDresField = new javax.swing.JTextField();
        jLabelScreenName = new javax.swing.JLabel();
        jLabelDeleteEq = new javax.swing.JLabel();
        jButtonDeleteEq = new javax.swing.JButton();
        jButtonMagazineListEq = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jEqNameField3.setText("Nazwa");
        jEqNameField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEqNameField3ActionPerformed(evt);
            }
        });

        jButtonAdd.setText("Dodaj");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonBack.setText("Cofnij");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jIDeqField.setText("numer ID");
        jIDeqField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIDeqFieldActionPerformed(evt);
            }
        });

        jLabelChooseIDeq.setText("Wprowadź numer ID sprzętu:");

        jLabelAddEq.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelAddEq.setText("Dodawanie sprzętu");

        jLabelSetEqName.setText("Wprowadź nazwę sprzętu:");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Numer ID sprzętu", "Nazwa sprzętu"
            }
        ));
        jScrollPane3.setViewportView(jTable);

        jLabel8.setText("Wprowadź numer ID rezerwacji:");

        jPutIDresField5.setText("numer ID");
        jPutIDresField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPutIDresField5ActionPerformed(evt);
            }
        });

        jButtonResListEq.setText("Lista sprzętów w wybranej rezerwacji");
        jButtonResListEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResListEqActionPerformed(evt);
            }
        });

        jLabelChooseIDres.setText("Wprowadź numer ID rezerwacji:");

        jIDresField.setText("numer ID");
        jIDresField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIDresFieldActionPerformed(evt);
            }
        });

        jLabelScreenName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelScreenName.setText("Sprzęt w rezerwacjach");

        jLabelDeleteEq.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelDeleteEq.setText("Usuwanie sprzętu");

        jButtonDeleteEq.setText("Usuń");
        jButtonDeleteEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteEqActionPerformed(evt);
            }
        });

        jButtonMagazineListEq.setText("Lista sprzętów w magazynie");
        jButtonMagazineListEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMagazineListEqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jButtonDeleteEq, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabelAddEq, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabelDeleteEq, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelSetEqName)
                                                .addGap(50, 50, 50)
                                                .addComponent(jEqNameField3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelChooseIDeq)
                                                .addGap(47, 47, 47)
                                                .addComponent(jIDeqField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelChooseIDres)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jIDresField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 416, Short.MAX_VALUE)
                        .addComponent(jButtonBack)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jButtonResListEq)
                                .addGap(38, 38, 38)
                                .addComponent(jButtonMagazineListEq))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPutIDresField5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(149, 149, 149)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelScreenName, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabelScreenName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabelAddEq, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelChooseIDres)
                            .addComponent(jIDresField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jIDeqField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelChooseIDeq))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jEqNameField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSetEqName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelDeleteEq, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDeleteEq))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jPutIDresField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonResListEq)
                            .addComponent(jButtonMagazineListEq))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBack)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jEqNameField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEqNameField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEqNameField3ActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jIDeqFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIDeqFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIDeqFieldActionPerformed

    private void jPutIDresField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPutIDresField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPutIDresField5ActionPerformed

    private void jButtonResListEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResListEqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonResListEqActionPerformed

    private void jIDresFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIDresFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIDresFieldActionPerformed

    private void jButtonDeleteEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteEqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeleteEqActionPerformed

    private void jButtonMagazineListEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMagazineListEqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMagazineListEqActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        this.setVisible(false);
        
        doctorMainGui.openScreen();
    }//GEN-LAST:event_jButtonBackActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonDeleteEq;
    private javax.swing.JButton jButtonMagazineListEq;
    private javax.swing.JButton jButtonResListEq;
    private javax.swing.JTextField jEqNameField3;
    private javax.swing.JTextField jIDeqField;
    private javax.swing.JTextField jIDresField;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelAddEq;
    private javax.swing.JLabel jLabelChooseIDeq;
    private javax.swing.JLabel jLabelChooseIDres;
    private javax.swing.JLabel jLabelDeleteEq;
    private javax.swing.JLabel jLabelScreenName;
    private javax.swing.JLabel jLabelSetEqName;
    private javax.swing.JTextField jPutIDresField5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
