/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.szpital;
import javax.swing.JOptionPane;
/**
 *
 * @author Lenovo
 */
public class ZastosowanieSal extends javax.swing.JFrame {

    private Ekran_ordynator_lekarz doctorMainGui;
    private RepoSal rooms;
    
    public ZastosowanieSal(Ekran_ordynator_lekarz screen, RepoSal r) {
        this.doctorMainGui = screen;
        this.rooms = r;
        initComponents();
    }

    //Funkcja aktualizująca i włączająca ekran 
    public void openScreen(){
        
        this.update();
        this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jButtonBack = new javax.swing.JButton();
        jButtonChangeType = new javax.swing.JButton();
        jLabelScreenName = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextChooseRoom = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable.setModel(new SalaTableModel(this.rooms.getRooms())
        );
        jTable.setToolTipText("");
        jScrollPane3.setViewportView(jTable);

        jButtonBack.setText("Cofnij");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jButtonChangeType.setText("Zmień typ");
        jButtonChangeType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeTypeActionPerformed(evt);
            }
        });

        jLabelScreenName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelScreenName.setText("Zastosowanie sal");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Operacyjna", "Intensywnej_Terapii", "Porodowa", "Zabiegowa", "Wypoczynkowa", "Psychiatryczna", "Rehabilitacyjna", "Magazyn", "Biuro", "Gabinet_Lekarski", "Gabinet_Pielegniarski", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextChooseRoom.setText("Wybierz nowy typ sali:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jTextChooseRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButtonChangeType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBack)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabelScreenName, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelScreenName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextChooseRoom)
                    .addComponent(jButtonChangeType)
                    .addComponent(jButtonBack)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        this.setVisible(false);
        
        doctorMainGui.openScreen();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonChangeTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeTypeActionPerformed
        int answear = JOptionPane.showConfirmDialog(this, "Na penwo chcesz edytować typ sali?", "Usuwanie sprzętu", JOptionPane.YES_NO_OPTION);
        if(answear == 0){
            if(jTable.getSelectedRowCount() == 1){

                String type = jComboBox1.getSelectedItem().toString();
                int key =(int) jTable.getValueAt(jTable.getSelectedRow(), 0);
                
                this.rooms.changeRoomType(type, key);
                
                this.update();
            } else{
                    if(jTable.getRowCount() == 0){
                    JOptionPane.showMessageDialog(this, "Tablica jest pusta");
                }else{
                    JOptionPane.showMessageDialog(this, "Prosze zaznaczyć tylko jedno salę do ");
                }
                this.update();
            }   
        } 
    }//GEN-LAST:event_jButtonChangeTypeActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

     private void update(){ 
        SalaTableModel model = (SalaTableModel) jTable.getModel();
        model.update();    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonChangeType;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabelScreenName;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel jTextChooseRoom;
    // End of variables declaration//GEN-END:variables
}
